[gen-disconnect-called-during-success.https.html]
  [disconnect() called during a getPrimaryService call that succeeds. Reject with NetworkError.]
    expected: FAIL

